# Makefile --

# The list of main sources.  Usually a single ".tex" file.
SOURCES		= conto-intesa-guida-etf.tex

# The list of PDF documents that must be generated.
DOCUMENTS	= $(patsubst %.tex, %.pdf, $(SOURCES))

# The list of LaTeX files automatically generated by C language programs, if any.
MY_CLANG_GENERATED_SOURCES	= \
	conto-intesa--calcoli-esempio--operazione-acquisto.inc				\
	conto-intesa--calcoli-esempio--saldo-acquisto.inc				\
	conto-intesa--calcoli-esempio--operazione-vendita.inc				\
	conto-intesa--calcoli-esempio--strategie-prezzi--metodo-media-ponderata.inc	\
	conto-intesa--calcoli-esempio--strategie-prezzi--metodo-linee-investimento.inc

# The list of files included by the main LaTeX sources, if any.
MY_DVI_PREREQUISITES		= \
	fdl-1.3.tex									\
	$(MY_CLANG_GENERATED_SOURCES)

# The list of source documents that need BibTeX processing.
BIBSOURCES	= conto-intesa-guida-etf.tex

# Executable  programs used  to generate  LaTeX include  files.  Every
# program should print to stdout the generated include file.
PROGRAMS	= \
	conto-intesa--calcoli-esempio--etf-abcd.exe					\
	conto-intesa--calcoli-esempio--etf-xyz.exe					\
	\
	conto-intesa--calcoli-esempio--operazione-acquisto.exe				\
	conto-intesa--calcoli-esempio--saldo-acquisto.exe				\
	conto-intesa--calcoli-esempio--operazione-vendita.exe				\
	conto-intesa--calcoli-esempio--rendimento-riepilogo.exe				\
	conto-intesa--calcoli-esempio--strategie-prezzi--metodo-media-ponderata.exe	\
	conto-intesa--calcoli-esempio--strategie-prezzi--metodo-linee-investimento.exe	\
	conto-intesa--calcoli-esempio--verifica-prezzo-pareggio.exe

%.exe: conto-intesa--calcoli-esempio.h

include ./Makefile-rules

### end of file
